source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Originate/CocoaPods.git'
use_frameworks!

target 'OriginateUI-Example' do
pod "OriginateUI", :path => "../"
end

target 'OriginateUI-Tests' do
pod "OriginateUI", :path => "../"
end