source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'OriginateUI-Example', :exclusive => true do
  pod "OriginateUI", :path => "../"
end

target 'OriginateUI-Tests', :exclusive => true do
  pod "OriginateUI", :path => "../"  
end
